name: Prerlease Build and Release to beta tag.
on:
    workflow_dispatch:
jobs:
  build:
    env:
        dllName: RockTheVote
        debugPath: /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/bin/Debug

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.0.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Install dependencies
      run: dotnet restore        

    - name: Build
      run: dotnet build  

    - name: Create zip
      run: cd ${debugPath} && mv net8.0 $dllName && zip -r ${dllName}.zip ${dllName}

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v0.0.0-beta
        release_name: Release Beta
        draft: false
        prerelease: true
        allowUpdates: true

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ${{env.debugPath}}/${{env.dllName}}.zip
        asset_name: ${{env.dllName}}_beta.zip
        asset_content_type: application/zip
